<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Destination;
use App\Models\DestinationType;
use App\Models\Region;
use App\Support\RichText;
use App\Support\Seo;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use Inertia\Inertia;

class PlaceController extends Controller
{
    /**
     * Display a listing of regions and destinations.
     */
    public function index()
    {
        $regions = Region::with(['destinations' => function ($query) {
            $query->with('types:id,name')->orderBy('name');
        }])
        ->withCount('destinations')
        ->ordered()
        ->get();

        return Inertia::render('Admin/Places/Index', [
            'regions' => $regions,
            'destinationTypes' => DestinationType::ordered()->get(['id', 'name']),
        ]);
    }

    /**
     * Save the order of the regions, given every region ID from first to last.
     */
    public function reorderRegions(Request $request)
    {
        $validated = $request->validate([
            'ids' => ['required', 'array', 'size:' . Region::count()],
            'ids.*' => ['integer', 'distinct', 'exists:regions,id'],
        ]);

        Region::reorder($validated['ids']);

        return redirect()->back()->with('success', 'Region order saved');
    }

    /**
     * Store a newly created region.
     */
    public function storeRegion(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'slug' => 'required|string|max:191|unique:regions,slug',
            'description' => 'nullable|string',
            'image' => 'nullable|string',
            // Empty meta fields are generated by the Region model
            'meta_title' => 'nullable|string|max:255',
            'meta_description' => 'nullable|string|max:' . Seo::DESCRIPTION_LENGTH,
        ]);

        $region = Region::create($validated);

        return redirect()->back()->with('success', 'Region created successfully');
    }

    /**
     * Update the specified region.
     */
    public function updateRegion(Request $request, Region $region)
    {
        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'slug' => 'required|string|max:191|unique:regions,slug,' . $region->id,
            'description' => 'nullable|string',
            'image' => 'nullable|string',
            // Empty meta fields are generated by the Region model
            'meta_title' => 'nullable|string|max:255',
            'meta_description' => 'nullable|string|max:' . Seo::DESCRIPTION_LENGTH,
        ]);

        $region->update($validated);

        return redirect()->back()->with('success', 'Region updated successfully');
    }

    /**
     * Remove the specified region.
     */
    public function destroyRegion(Region $region)
    {
        $region->delete();

        return redirect()->back()->with('success', 'Region deleted successfully');
    }

    /**
     * Store a newly created destination.
     */
    public function storeDestination(Request $request)
    {
        $validated = $request->validate([
            'region_id' => 'required|exists:regions,id',
            'name' => 'required|string|max:255',
            'slug' => 'required|string|max:191|unique:destinations,slug',
            'description' => 'nullable|string',
            'featured_image' => 'nullable|string',
            'latitude' => 'nullable|numeric',
            'longitude' => 'nullable|numeric',
            'best_time_to_visit' => 'nullable|string',
            'average_cost' => 'nullable|string',
            'is_featured' => 'boolean',
            'types' => 'array',
            'types.*' => 'integer|exists:destination_types,id',
        ]);
        $validated['description'] = RichText::sanitize($validated['description'] ?? null);

        $destination = Destination::create(Arr::except($validated, 'types'));
        $destination->types()->sync($validated['types'] ?? []);

        return redirect()->back()->with('success', 'Destination created successfully');
    }

    /**
     * Update the specified destination.
     */
    public function updateDestination(Request $request, Destination $destination)
    {
        $validated = $request->validate([
            'region_id' => 'required|exists:regions,id',
            'name' => 'required|string|max:255',
            'slug' => 'required|string|max:191|unique:destinations,slug,' . $destination->id,
            'description' => 'nullable|string',
            'featured_image' => 'nullable|string',
            'latitude' => 'nullable|numeric',
            'longitude' => 'nullable|numeric',
            'best_time_to_visit' => 'nullable|string',
            'average_cost' => 'nullable|string',
            'is_featured' => 'boolean',
            'types' => 'array',
            'types.*' => 'integer|exists:destination_types,id',
        ]);
        $validated['description'] = RichText::sanitize($validated['description'] ?? null);

        $destination->update(Arr::except($validated, 'types'));
        $destination->types()->sync($validated['types'] ?? []);

        return redirect()->back()->with('success', 'Destination updated successfully');
    }

    /**
     * Remove the specified destination.
     */
    public function destroyDestination(Destination $destination)
    {
        $destination->delete();

        return redirect()->back()->with('success', 'Destination deleted successfully');
    }
}